export const ADD_DRIVING_LICENCES = 'ADD_DRIVING_LICENCES';
export const ADD_LINKS = 'ADD_LINKS';
export const ADD_HOBBIES = 'ADD_HOBBIES';
export const ADD_LANGUAGES = 'ADD_LANGUAGES';
export const ADD_ABILITIES = 'ADD_ABILITIES';
export const ADD_SCHOOLS = 'ADD_SCHOOLS';
export const ADD_PROJECTS = 'ADD_PROJECTS';
export const ADD_COMMUNITIES = 'ADD_COMMUNITIES';
export const ADD_COMPANIES = 'ADD_COMPANIES';
export const ADD_REFERENCES = 'ADD_REFERENCES';

export const NAME = 'NAME';
export const TEL_NUMBER = 'TEL_NUMBER';
export const EMAIL = 'EMAIL';
export const CITY = 'CITY';
export const JOB = 'JOB';
export const GENDER = 'GENDER';
export const POSTALCODE = 'POSTALCODE';


export const REMOVE_DRIVING_LICENCES = 'REMOVE_DRIVING_LICENCES';
export const REMOVE_LINKS = 'REMOVE_LINKS';
export const REMOVE_HOBBIES = 'REMOVE_HOBBIES';
export const REMOVE_LANGUAGES = 'REMOVE_LANGUAGES';
export const REMOVE_ABILITIES = 'REMOVE_ABILITIES';
export const REMOVE_SCHOOLS = 'REMOVE_SCHOOLS';
export const REMOVE_PROJECTS = 'REMOVE_PROJECTS';
export const REMOVE_COMMUNITIES = 'REMOVE_COMMUNITIES';
export const REMOVE_COMPANIES = 'REMOVE_COMPANIES';
export const REMOVE_REFERENCES = 'REMOVE_REFERENCES';

export const SELECTED_CV = 'SELECTED_CV';
export const SELECTED_CV_COLOR = 'SELECTED_CV_COLOR';